#pragma config(Hubs,  S4, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S4,     ,                    sensorHiTechnicTouchMux)
#pragma config(Motor,  mtr_S3_C1_1,     motorD,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S3_C1_2,     motorE,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S3_C2_1,     motorF,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S3_C2_2,     motorG,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S3_C3_1,     motorH,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S3_C3_2,     motorI,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S3_C4_1,     motorJ,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S3_C4_2,     motorK,        tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool initDone = false; //we arent initialized
bool rightH; //right helicopter touch sensor
bool leftH;//left helicopter touch sensor
bool touchFS;//swinger touch sensor
task RH(){//spin helicopter right
  time1[T2] = 0;//set time to 0
  if(initDone){//if we are initialized
    while(!rightH && time1[T2] < 2000){//if we hit touch sensor or it timesout
      motor[motorD] = 100;//run motor full speed
    }
    motor[motorD] = 0;//stop motor
  }
}
task main(){
  initDone = true;//finished init
  StartTask(RH);//run helicopter
  while(true){
    int nmask = SensorValue[S4];//get raw sensor
    if(nmask & 0x01){//get swinger touch sensor state
      touchFS = true;
    }else{
      touchFS = false;
    }
    if(nmask & 0x02){//get left helicopter touch sensor state
      leftH = true;
    }else{
      leftH = false;
    }
    if(nmask & 0x04){//get right helicopter touch sensor state
      rightH = true;
    }else{
      rightH = false;
    }
  }
}
