#pragma config(Hubs,  S4, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Motor,  motorA,          a,             tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorB,          b,             tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S4_C1_1,     motorD,        tmotorNone, openLoop)
#pragma config(Motor,  mtr_S4_C1_2,     motorE,        tmotorNone, openLoop)
#pragma config(Motor,  mtr_S4_C2_1,     motorF,        tmotorNone, openLoop)
#pragma config(Motor,  mtr_S4_C2_2,     motorG,        tmotorNone, openLoop)
#pragma config(Motor,  mtr_S4_C3_1,     motorH,        tmotorNone, openLoop)
#pragma config(Motor,  mtr_S4_C3_2,     motorI,        tmotorNone, openLoop)
#pragma config(Motor,  mtr_S4_C4_1,     motorJ,        tmotorNone, openLoop)
#pragma config(Motor,  mtr_S4_C4_2,     motorK,        tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
  while(true){
    motor[motorD] = 100; //set motor d to power 100
  }
}
