#pragma config(Motor,  motorA,          frontRight,    tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int FR = 0;

void updateMotors(){
  motor[frontRight] = FR;
}

task main(){
  FR = 0; //front right wheel to power 0
  for(int i; i<100; i++){ //creates for loop to run until i = 100
    FR=i; //set FR to power i
    wait1Msec(100); //wait for 1/100 of a sec
    updateMotors(); //update the motors
  }
  for(int i=100; i>0; i--) //creates for loop to run until i = 0
  {
    FR=i; //set fr to power i
    wait1Msec(100); //wait 1/100 of a second
    updateMotors(); //update the motors
  }
}
