#pragma config(Sensor, S1,     EEPROM,              sensorI2CCustomStd)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
 * $Id: EEPROM-test1.c 21 2010-02-17 10:19:42Z xander $
 */

/**
 * EEPROM-driver.h provides an API for the AT24C512, 24AA512 and 24AA1025 EEPROMs.  This program
 * demonstrates how to use that API.
 *
 * License: You may use this code as you wish, provided you give credit where it's due.
 *
 * THIS CODE WILL ONLY WORK WITH ROBOTC VERSION 2.00 AND HIGHER.
 * Xander Soldaat (mightor_at_gmail.com)
 * 31 May 2009
 * version 0.1
 */
#include "drivers/common.h"
#include "drivers/EEPROM-driver.h"

//tByteArray data;

task main () {
  string w_string = "MindstormsNXT";
  string r_string;
  tByteArray data;

  memcpy(data.arr[0], w_string, sizeof(w_string));
  EEPROMwriteBytes(EEPROM, 0, data, 13);
  // After a write, you *must* wait 5 msec
  wait1Msec(5);

  eraseDisplay();
  memset(data, 0, sizeof(tByteArray));
  EEPROMreadBytes(EEPROM, 0, data, 13);
  // Make sure the string is 0 terminated.
  data.arr[13] = 0;
  StringFromChars(r_string, data.arr);

  nxtDisplayTextLine(1, "%s", r_string);
  wait1Msec(2000);
}

/*
 * $Id: EEPROM-test1.c 21 2010-02-17 10:19:42Z xander $
 */
