#pragma config(Sensor, S1,     LLEADER,             sensorLowSpeed9v)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
 * $Id: MSLL-test2.c 20 2009-12-08 22:59:13Z xander $
 */

/**
 * MSLL-driver.h provides an API for the Mindsensors LineLeader Sensor.  This program
 * demonstrates how to use that API.
 *
 * Changelog:
 * - 0.1: Initial release
 * - 0.2: More comments
 *
 * Credits:
 * - Big thanks to Mindsensors for providing me with the hardware necessary to write and test this.
 *
 * License: You may use this code as you wish, provided you give credit where it's due.
 *
 * THIS CODE WILL ONLY WORK WITH ROBOTC VERSION 2.00 AND HIGHER.
 * Xander Soldaat (mightor_at_gmail.com)
 * 28 November 2009
 * version 0.2
 */

#include "drivers/common.h"
#include "drivers/MSLL-driver.h"

task main {
  byte sensor = 0;
  tByteArray signalstr;

  while (true) {
    // Fetch the data from the sensor
    sensor = LLreadResult(LLEADER);

    // Read the raw sensor data (8 bit data)
    LLreadSensorRaw(LLEADER, signalstr);

    // This clears the entire area occupied by the small rectangles
    nxtEraseRect(6,62, 91, 43);
    for (int i = 0; i < 8; i++) {
      // Draw the rectangles for the signal strength first
      nxtDrawRect(6+(i*11),62, 14+(i*11), 50);
      nxtFillRect(6+(i*11),51+signalstr.arr[i]/10, 14+(i*11), 50);
      // Draw a black rectangle if the sensor has detected the line,
      // a hollow one when nothing has been detected.
      if ((sensor >> i) & 1) {
        nxtFillRect(6+(i*11),48, 14+(i*11), 43);
      } else {
        nxtDrawRect(6+(i*11),48, 14+(i*11), 43);
      }
    }
    // Display the actual signal strength for each sensor
    for (int i = 0; i < 7; i+=2) {
      nxtDisplayTextLine(i/2+3, "S: %3d S: %3d", ubyteToInt(signalstr.arr[i]), ubyteToInt(signalstr.arr[i+1]));
    }
    wait1Msec(50);
  }
}

/*
 * $Id: MSLL-test2.c 20 2009-12-08 22:59:13Z xander $
 */
