#pragma config(Sensor, S1,     LLEADER,             sensorLowSpeed9v)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
 * $Id: MSLL-test4.c 20 2009-12-08 22:59:13Z xander $
 */

 /** \file MSLL-test3.c
 * \brief Mindsensors LineLeader Sensor demo program
 *
 * MSLL-test3.c is a demo program for the Mindsensors LineLeader Sensor.
 *
 * Changelog:
 * - 0.1: Initial release
 * - 0.2: More comments
 *
 * Credits:
 * - Big thanks to Mindsensors for providing me with the hardware necessary to write and test this.
 *
 * License: You may use this code as you wish, provided you give credit where its due.
 *
 * THIS CODE WILL ONLY WORK WITH ROBOTC VERSION 2.00 AND HIGHER.
 * Xander Soldaat (mightor_at_gmail.com)
 * 28 November 2009
 * version 0.2
 */

#include "drivers/common.h"
#include "drivers/MSLL-driver.h"

task main {
  byte sensor = 0;
  tIntArray signalstr;

  while (true) {
    // Fetch the data from the sensor.  These are the 16 bit raw AD values.
    LLreadSensorUncalibrated(LLEADER, signalstr);

    // Display the actual signal strength for each sensor
    for (int i = 0; i < 7; i++) {
      nxtDisplayTextLine(i, "S[%d]: %5d", i, signalstr.arr[i]);
    }
    wait1Msec(50);
  }
}

/*
 * $Id: MSLL-test4.c 20 2009-12-08 22:59:13Z xander $
 */
